### PR TITLE
Fix expansion names to they match the FFG site

### PR DESCRIPTION
**Pull request by FreakyDug**
-wing stopped being capitalised with the K-wing
-class in Lambda-class Shuttle Expansion Pack isn't capitlised even though it is on the cards

### CODE REVIEW

**Comment by dhdasilva** [comment]
Although some "wings" expansion packs are capitalized at the FFG site, like "E-Wing" for example, all of them are not capitalized at the boxes.

Besides that, if you look at the expansion pack's little description, you'll see that FFG always refers to the ships with "wings" not capitalized too.

I think we should change all the "wings" expansion packs and ships to match their boxes and descriptions, or keep them the way they are. Some capitalized and some not are ugly and inconsistent. What do you think?

**Comment by FreakyDug** [comment]
It's super inconsistent. 

The game itself it's consistently referred to as X-Wing by FFG, but the logo has all the characters in wing the same size (though they're all actually capitals, just a smaller capital than the X. Plus Lucasfilm doesn't capitalise the W (http://www.starwars.com/databank/x-wing-starfighter).

The description for the X-Wing Expansion Pack refers to the ship with a lower case w but to the expansion and game with an upper case W. But for the K-wing pack's description, the ship and the expansion are lower case w but the game is still upper case.

In game, all the cards have all the letters in wing the same size, as far as I can see.

I assumed, because some were already inconsistent and matched the site that that's what was being aimed for, but I'd be happy to standardise it (to lowercase, to match more recent expansions and the cards). Then I can do the same to the pages on the wiki so my links work. :)

**Comment by guidokessels** [comment]
When typing the names I tried to keep the same capitalisation as the cards.

I just checked FFG's website and the capitalisation of the expansion packs is all over the place, so I suggest we ignore what FFG does and follow the spelling from the official Star Wars Databank where both `-wing` and `-class` are lowercase:
[Databank: X-wing](http://www.starwars.com/databank/x-wing-starfighter)
[Databank: Lambda-class Shuttle](http://www.starwars.com/databank/imperial-shuttle)
[Databank: Sheathipede-class Shuttle](http://www.starwars.com/databank/phantom-ii)

**Comment by guidokessels** [comment]
I suggest we make `-wing` and `-class` lowercase everywhere (not just the expansion packs). This includes:
- All json files
- All image folders

@FreakyDug Does this work for you? Let me know if you want to do this or if I should do it.

**Comment by FreakyDug** [comment]
@guidokessels Agreed. I can do it this evening and update this PR, unless you want to do it sooner.

**Comment by guidokessels** [comment]
@FreakyDug That sounds good, thanks 👍

**Comment by dhdasilva** [comment]
Besides the problems with `-wing` and `-class` ships, there is also the `TIE`'s one. Although they are consistent by FFG, always having the word after "TIE" capitalized, they are all lowercased on the SW Databank, Wikipedia and Wookieepedia (`TIE fighter` instead of `TIE Fighter`, for example). Should we change them too, or keep it the way they are, since they are at least consistent?

**Comment by FreakyDug** [comment]
I think where FFG are consistent (cards, expansion name, etc.) it makes sense to copy them. The names FFG uses don't always match the names in other sources. Eg. FFG uses "Kihraxz Fighter" but Wookieepedia has "Kihraxz assault fighter". Would we just change the case or add the "assault" as well?

**Comment by FreakyDug** [comment]
Firstly, I can't figure out why the tests failed, I changed the directory names and the file paths in pilots.js and they pass for me locally. Any ideas?

Secondly, there are two weird ones: A-wing Test Pilot and B-wing/E2. The card title text has the W uppercase (even though the ship restriction on that same card is lowercase). Should we stick with that or go for consistency?

**Comment by guidokessels** [comment]
You'll have to rename the image folders. So `images/pilots/Rebel Alliance/X-Wing` should be `images/pilots/Rebel Alliance/X-wing`. I'm not sure why it works for you locally. It shouldn't.

**Comment by FreakyDug** [comment]
Oh huh, all my moves have disappeared from the commit. 😕 The directories are all renamed on my local filesystem, but moves aren't showing in the github client any more. I'll try redoing it on Linux, it's probably Windows and its case-insensitive file system shenanigans.

**Comment by FreakyDug** [comment]
Sorry about the mess, I was lazy and didn't want to install node to run the tests.

**Comment by guidokessels** [comment]
Thanks @FreakyDug, excellent work!

**Pull request merged**
